# vim:tw=70
Summary:	Collection of tools to help you analyze qmail's activity record.
Name:		qmailanalog
Version:	0.70
Release:	0.5
Epoch:		0
License:	ASIS
Group:		Applications/Mail
Source0:	http://cr.yp.to/software/%{name}-%{version}.tar.gz
# Source0-md5:	84a3d44cbf2dbd88e8b97edd98c65732
Source1:	http://archives.eyrie.org/software/ARCHIVE/tai64nfrac/tai64nfrac-1.3.tar.gz
# Source1-md5:	27c0b2262e108d2d97218b49f1962581
Patch0:		%{name}-errno.patch
URL:		http://cr.yp.to/qmailanalog.html
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

# Not FHS compliant
%define		_prefix	/var/qmail
%define		_mandir /usr/share/man

%description
Collection of tools to help you analyze qmail's activity record.

The qmailanalog also includes several tools to focus attention on
particular senders, recipients, or messages. 

This package also contains tai64nfrac, which given data with TAI64N
timestamps as input (such as data generated by multilog), will convert
those times to seconds since epoch (with a fractional part) and
otherwise output the same data.

%prep
%setup -q -a1
%patch0 -p0

%build
echo "%{_prefix}" > conf-home
echo "%{__cc} %{rpmcflags}" > conf-cc
echo "%{__cc} %{rpmldflags}" > conf-ld

%{__make}

%{__make} \
	-C tai64nfrac-1.3 \
	CC=%{__cc} \
	CFLAGS="%{rpmcflags}" \
	LDFLAGS="%{rpmldflags}" \

%install
rm -rf $RPM_BUILD_ROOT
install -d $RPM_BUILD_ROOT{%{_bindir},%{_mandir}/man1}

install \
	columnt ddist deferrals failures matchup recipients rhosts \
	rxdelay senders successes suids xqp xrecipient xsender \
	zddist zdeferrals zfailures zoverall zrecipients zrhosts \
	zrxdelay zsenders zsendmail zsuccesses zsuids \
	$RPM_BUILD_ROOT%{_bindir}

install tai64nfrac-1.3/tai64nfrac $RPM_BUILD_ROOT%{_bindir}
install tai64nfrac-1.3/*.1 $RPM_BUILD_ROOT%{_mandir}/man1

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(644,root,root,755)
%doc README THANKS TODO
%doc MATCHUP ACCOUNTING BLURB
%attr(755,root,root) %{_bindir}/*
%{_mandir}/man1/*
